"""change User last_login column to last_seen column.

Revision ID: 0e34b84c409b
Revises: 0458a8fa93fa
Create Date: 2023-05-04 14:48:51.641711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e34b84c409b'
down_revision = '0458a8fa93fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
