"""Add about_me column (280 char max) in User table.

Revision ID: 22c1d68ed97d
Revises: 9a0e18f788c0
Create Date: 2023-04-29 12:27:21.419481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c1d68ed97d'
down_revision = '9a0e18f788c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
