"""Fix single comment per post problem second try.

Revision ID: 5f35462c4e36
Revises: 9ab694b4da44
Create Date: 2023-05-01 18:24:51.295623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f35462c4e36'
down_revision = '9ab694b4da44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
