"""update followers

Revision ID: 9ab694b4da44
Revises: 22c1d68ed97d
Create Date: 2023-05-01 16:52:35.385274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab694b4da44'
down_revision = '22c1d68ed97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='fk_follows_followed_id_users'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_follows_follower_id_users'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name='pk_follows')
    )
    # ### end Alembic commands ###
